### ISSUE TITLE
Advice on usage?

### ISSUE THREAD

**Issue by cnk113** [UPSUTER/GEMLI#1]
Hello,

Looking through the README, I wanted to clarify if we wanted to use clonal barcoded datasets where the clone sizes are larger >50 cells and wanted to break it further. 
Would you recommend running predict_lineages on the dataset after subsetting on a specific clone? 
Ideally suggest_network_trimming_to_size could perhaps maybe leverage existing barcoded clonal information?

Thanks,
Chang

**Comment by MarcelTarbier** [comment]
I think in this specific case I would recommend running predict_lineages on each clone individually. Will yield better results than running on all. Good luck and let us know if there is anything else! Best wishes, Marcel

**Comment by MarcelTarbier** [comment]
Network trimming is intended for sets where you don't have the information but have a feeling for how big the lineages should be (what size they should not exceed).
